(() => {
  const KEY='prime-rp-site-v1';
  const LOCAL_ADMIN_PASSWORD='primerp@algerie';
  const defaults={status:'online',players:128,products:[
    {id:1,name:'عضوية VIP',description:'مزايا حصرية ومكافآت يومية.',price:'500 نقطة',icon:'✦'},
    {id:2,name:'سيارة مميزة',description:'اختر مركبتك ولفت الأنظار في المدينة.',price:'800 نقطة',icon:'🚘'},
    {id:3,name:'منزل الأحلام',description:'مساحتك الخاصة في قلب Los Santos.',price:'1,200 نقطة',icon:'⌂'}
  ],suggestions:[],staff:[{id:'1012048571938476042',name:'صهيب',role:'إدارة عليا'},{id:'934851204758192640',name:'يوسف',role:'إدارة السيرفر'},{id:'812057349182043146',name:'فريق الدعم',role:'دعم فني'}]};
  const rules=[['01','احترام الجميع','التزم بالاحترام داخل وخارج المدينة، وابتعد عن الإساءة أو التحرش.'],['02','تقمّص الشخصية','حافظ على واقعية شخصيتك ولا تخلط بين أحداث اللعب والحياة الواقعية.'],['03','الحياة ثمينة','قدّر حياة شخصيتك وتعامل مع المواقف الخطرة بواقعية.'],['04','منع استغلال الأخطاء','لا تستغل الثغرات أو البرامج الخارجية، وأبلغ الإدارة عن أي خلل.'],['05','قوانين السطو','خطط للسطو بشكل منطقي، والتزم بعدد المشاركين وشروط التفاوض.'],['06','قوانين الشارع','حافظ على تسلسل الأحداث، ولا تبدأ العنف دون سبب أو تفاعل مناسب.'],['07','المركبات والقيادة','قد السيارة بواقعية، واحترم المشاة وقواعد المرور داخل المدينة.'],['08','التعاون مع الإدارة','اتبع تعليمات الطاقم وقدّم البلاغات بهدوء مع الأدلة المتاحة.']];
  let data;try{data={...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{data={...defaults}}
  let backendEnabled=false,currentUser=null;
  const save = () => {
  try {
    localStorage.setItem(KEY, JSON.stringify(data));
    if (window.db) {
      window.db.collection("site").doc("primeRPData").set(data)
        .then(() => console.log("Sauvegardé sur Firebase !"))
        .catch(err => console.error("Erreur Firebase:", err));
    }
  } catch(e) {}
};
  const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const imageFileToDataUrl=file=>new Promise((resolve,reject)=>{if(!file||!file.type.startsWith('image/'))return reject(new Error('اختر ملف صورة صالحاً.'));const reader=new FileReader();reader.onerror=()=>reject(new Error('تعذرت قراءة الصورة.'));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error('صيغة الصورة غير مدعومة.'));img.onload=()=>{const scale=Math.min(1,1000/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.78))};img.src=reader.result};reader.readAsDataURL(file)});
  const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
  function render(){
    $('#rulesGrid').innerHTML=rules.map(([n,t,d])=>`<article class="rule-card"><span class="rule-number">RULE — ${n}</span><h3>${t}</h3><p>${d}</p></article>`).join('');
    const symbols=['✦','🚘','⌂','♛','✧'];$('#storeGrid').innerHTML=data.products.length?data.products.map((p,i)=>`<article class="product-card"><div class="product-art ${p.image?'has-image':''}">${p.image?`<img src="${p.image}" alt="${escapeHtml(p.name)}">`:''}<span>${p.image?'':escapeHtml(p.icon||symbols[i%symbols.length])}</span></div><div class="product-info"><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.description)}</p><div class="product-bottom"><span class="product-price">${escapeHtml(p.price)}</span><a class="product-buy" href="https://discord.gg/sY3wRvwGE" target="_blank" rel="noreferrer">اطلب عبر Discord ↗</a></div></div></article>`).join(''):'<p class="empty-state">لا توجد منتجات حالياً.</p>';
    $('#suggestionTotal').textContent=`${data.suggestions.length} اقتراحات`;
    const labels={pending:'قيد المراجعة',accepted:'مقبول',rejected:'مرفوض'};
    $('#suggestionList').innerHTML=data.suggestions.length?data.suggestions.slice().reverse().map(s=>`<article class="suggestion-item"><div><b>${escapeHtml(s.name||'لاعب المدينة')}</b><span class="badge ${s.status}">${labels[s.status]||labels.pending}</span></div><p>${escapeHtml(s.text)}</p></article>`).join(''):'<div class="empty-state">كن أول من يشارك فكرة مع المجتمع.</div>';
    $('#staffGrid').innerHTML=data.staff.length?data.staff.map(s=>`<article class="staff-card"><div class="staff-avatar ${s.image?'has-image':''}">${s.image?`<img src="${s.image}" alt="صورة ${escapeHtml(s.name)}">`:escapeHtml((s.name||'?').slice(0,1))}</div><h3>${escapeHtml(s.name)}</h3><p>${escapeHtml(s.role)}</p><div class="staff-id">DISCORD · ${escapeHtml(s.id)}</div></article>`).join(''):'<div class="empty-state">سيتم الإعلان عن أعضاء الفريق قريباً.</div>';
    const states={online:['السيرفر متصل','متصل الآن · '+data.players+' لاعباً'],offline:['السيرفر غير متصل','نراك قريباً'],maintenance:['السيرفر تحت الصيانة','نعمل على تحسين تجربتك']};const state=states[data.status]||states.online;
    $('#statusLabel').textContent=state[0];$('#playerCount').textContent=state[1];$('.status-dot').style.background=data.status==='online'?'#26d795':data.status==='maintenance'?'#d5b775':'#fa7380';$('.status-dot').style.boxShadow=`0 0 12px ${data.status==='online'?'#26d795':data.status==='maintenance'?'#d5b775':'#fa7380'}`;
  }
  function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2400)}
  async function connectBackend(){try{const [stateResponse,meResponse]=await Promise.all([fetch('/api/state',{cache:'no-store'}),fetch('/api/me',{cache:'no-store'})]);if(!stateResponse.ok||!meResponse.ok)return;data={...defaults,...await stateResponse.json()};currentUser=(await meResponse.json()).user;backendEnabled=true;render();if(currentUser?.admin){$('#adminLogin').hidden=true;$('#adminPanel').hidden=false}}catch{}}
  render();
  connectBackend();setInterval(async()=>{if(!backendEnabled)return;try{const r=await fetch('/api/state',{cache:'no-store'});if(r.ok){data={...defaults,...await r.json()};render()}}catch{}} ,20000);
  $('#copyIp').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('mtasa://5.39.63.207:6014');toast('تم نسخ عنوان السيرفر')}catch{toast('mtasa://5.39.63.207:6014')}});
  const audio=$('#themeAudio');audio.play().catch(()=>{const startOnce=()=>{audio.play().catch(()=>{});window.removeEventListener('pointerdown',startOnce);window.removeEventListener('keydown',startOnce)};window.addEventListener('pointerdown',startOnce,{once:true});window.addEventListener('keydown',startOnce,{once:true})});window.addEventListener('pagehide',()=>audio.pause());window.addEventListener('pageshow',()=>{if(!document.hidden)audio.play().catch(()=>{})});document.addEventListener('visibilitychange',()=>{if(document.hidden)audio.pause();else audio.play().catch(()=>{})});
  $('#adminLogout').addEventListener('click',async()=>{await fetch('/auth/logout',{method:'POST'}).catch(()=>{});currentUser=null;$('#adminPanel').hidden=true;$('#adminLogin').hidden=false;$('#adminPassword').value='';$('#adminError').textContent='';toast('تم قفل لوحة الإدارة')});
  $('#suggestionForm').addEventListener('submit',async e=>{e.preventDefault();const text=$('#suggestionText').value.trim();if(!text)return;const suggestion={name:$('#suggestionName').value.trim()||'لاعب المدينة',text};try{if(backendEnabled){const r=await fetch('/api/suggestions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(suggestion)});if(!r.ok)throw Error('تعذر إرسال الاقتراح.');const s=await fetch('/api/state',{cache:'no-store'});data={...defaults,...await s.json()}}else data.suggestions.push({id:Date.now(),...suggestion,status:'pending'});if(!backendEnabled)save();render();$('#suggestionText').value='';$('#suggestionNote').textContent='وصل اقتراحك، شكراً لمشاركتنا!';setTimeout(()=>$('#suggestionNote').textContent='',4000)}catch(err){$('#suggestionNote').textContent=err.message||'تعذر إرسال الاقتراح.'}});
  $('.menu-toggle').addEventListener('click',()=>$('.nav').classList.toggle('open'));$$('.nav a').forEach(a=>a.addEventListener('click',()=>$('.nav').classList.remove('open')));
  const dialog=$('#adminDialog');$('#adminOpen').addEventListener('click',()=>{dialog.showModal();$('#adminLogin').hidden=!!currentUser?.admin;$('#adminPanel').hidden=!currentUser?.admin;$('#adminError').textContent='';if(currentUser?.admin)adminTab('overview')});$$('[data-close]').forEach(b=>b.addEventListener('click',()=>dialog.close()));
  $('#adminLoginForm').addEventListener('submit',async e=>{e.preventDefault();$('#adminError').textContent='';const password=$('#adminPassword').value;try{if(backendEnabled){const response=await fetch('/auth/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(!response.ok){const err=await response.json().catch(()=>({}));throw new Error(err.error||'رمز الإدارة غير صحيح.')}}else if(password!==LOCAL_ADMIN_PASSWORD)throw new Error('رمز الإدارة غير صحيح.');currentUser={admin:true,local:!backendEnabled};$('#adminPassword').value='';$('#adminLogin').hidden=true;$('#adminPanel').hidden=false;adminTab('overview');toast('تم فتح لوحة الإدارة')}catch(err){$('#adminError').textContent=err.message||'رمز الإدارة غير صحيح.'}});
  $$('.admin-tabs button').forEach(b=>b.addEventListener('click',()=>adminTab(b.dataset.tab)));
  function adminTab(tab){$$('.admin-tabs button').forEach(b=>b.classList.toggle('selected',b.dataset.tab===tab));const root=$('#adminContent');
    if(tab==='overview'){root.innerHTML=`<div class="admin-row"><div><b>حالة السيرفر</b><small>تظهر الحالة في الواجهة الرئيسية</small></div><select id="statusSelect" class="admin-select"><option value="online">متصل</option><option value="offline">غير متصل</option><option value="maintenance">صيانة</option></select></div><div class="admin-row"><div><b>عدد اللاعبين</b><small>رقم توضيحي، يلزم API للمزامنة الحية</small></div><input id="playersInput" type="number" min="0" max="9999" class="admin-select" value="${data.players}" style="width:90px"></div><button class="admin-submit" id="saveOverview">حفظ الحالة</button>`;$('#statusSelect').value=data.status;$('#saveOverview').onclick=()=>{data.status=$('#statusSelect').value;data.players=Math.max(0,Number($('#playersInput').value)||0);save();render();toast('تم تحديث حالة السيرفر')};}
    if(tab==='products'){root.innerHTML=`<form class="admin-form" id="productForm"><input name="name" placeholder="اسم المنتج" required><input name="price" placeholder="السعر" required><input name="description" placeholder="وصف مختصر"><label class="upload-control">صورة المنتج <input name="image" type="file" accept="image/*"></label><button class="admin-submit">إضافة منتج</button></form><small class="upload-help">اختر صورة من جهازك؛ تُحفظ نسخة مضغوطة على الخادم.</small>${data.products.map(p=>`<div class="admin-row"><div><b>${escapeHtml(p.name)}</b><small>${escapeHtml(p.price)}</small></div><div class="admin-actions"><button data-toggle-edit="${p.id}">تعديل</button><button data-delete-product="${p.id}">حذف</button></div><form class="admin-edit-product" data-edit-product="${p.id}" hidden><input name="name" value="${escapeHtml(p.name)}" placeholder="الاسم" required><input name="price" value="${escapeHtml(p.price)}" placeholder="السعر" required><input name="description" value="${escapeHtml(p.description)}" placeholder="الوصف"><label class="upload-control">استبدال الصورة <input name="image" type="file" accept="image/*"></label><button class="admin-submit">حفظ التعديل</button></form></div>`).join('')||'<div class="empty-state">لا توجد منتجات.</div>'}`;$('#productForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const file=f.get('image');const image=file?.size?await imageFileToDataUrl(file):'';data.products.push({id:Date.now(),name:f.get('name').trim(),price:f.get('price').trim(),description:f.get('description').trim(),icon:'✦',image});save();render();adminTab('products');toast('تمت إضافة المنتج وحفظه')}catch(err){toast(err.message||'تعذر حفظ الصورة؛ جرب صورة أصغر')}};$$('[data-toggle-edit]').forEach(b=>b.onclick=()=>{const form=$(`[data-edit-product="${b.dataset.toggleEdit}"]`);form.hidden=!form.hidden});$$('[data-edit-product]').forEach(form=>form.onsubmit=async e=>{e.preventDefault();const p=data.products.find(x=>x.id===Number(form.dataset.editProduct));if(!p)return;const f=new FormData(form);try{const file=f.get('image');if(file?.size)p.image=await imageFileToDataUrl(file);p.name=f.get('name').trim();p.price=f.get('price').trim();p.description=f.get('description').trim();save();render();adminTab('products');toast('تم تحديث المنتج وحفظه')}catch(err){toast(err.message||'تعذر حفظ الصورة؛ جرب صورة أصغر')}});$$('[data-delete-product]').forEach(b=>b.onclick=()=>{data.products=data.products.filter(p=>p.id!==Number(b.dataset.deleteProduct));save();render();adminTab('products')});}
    if(tab==='suggestions'){const labels={pending:'قيد المراجعة',accepted:'مقبول',rejected:'مرفوض'};root.innerHTML=data.suggestions.length?data.suggestions.map(s=>`<div class="admin-row"><div><b>${escapeHtml(s.name)}</b><small>${escapeHtml(s.text)}</small></div><div class="admin-actions"><select class="admin-select" data-suggestion="${s.id}"><option value="pending">قيد المراجعة</option><option value="accepted">مقبول</option><option value="rejected">مرفوض</option></select></div></div>`).join(''):'<div class="empty-state">لا توجد اقتراحات بعد.</div>';$$('[data-suggestion]').forEach(sel=>{const s=data.suggestions.find(x=>x.id===Number(sel.dataset.suggestion));sel.value=s.status||'pending';sel.onchange=()=>{s.status=sel.value;save();render();toast('تم تحديث حالة الاقتراح')}})}
    if(tab==='staff'){root.innerHTML=`<form class="admin-form" id="staffForm"><input name="name" placeholder="اسم العرض" required><input name="id" placeholder="Discord ID" required><input name="role" placeholder="الرتبة" required><label class="upload-control">صورة العضو <input name="image" type="file" accept="image/*"></label><button class="admin-submit">إضافة عضو</button></form><small class="upload-help">اختر صورة من جهازك؛ تُحفظ نسخة مضغوطة في هذا المتصفح.</small>${data.staff.map(s=>`<div class="admin-row"><div><b>${escapeHtml(s.name)} · ${escapeHtml(s.role)}</b><small>Discord ID: ${escapeHtml(s.id)}</small></div><button class="admin-submit" data-delete-staff="${escapeHtml(s.id)}">حذف</button></div>`).join('')}`;$('#staffForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const file=f.get('image');const image=file?.size?await imageFileToDataUrl(file):'';data.staff.push({name:f.get('name').trim(),id:f.get('id').trim(),role:f.get('role').trim(),image});save();render();adminTab('staff');toast('تمت إضافة عضو الفريق وحفظه')}catch(err){toast(err.message||'تعذر حفظ الصورة؛ جرب صورة أصغر')}};$$('[data-delete-staff]').forEach(b=>b.onclick=()=>{data.staff=data.staff.filter(s=>s.id!==b.dataset.deleteStaff);save();render();adminTab('staff')});}
  }
// المزامنة والقراءة المباشرة من Firebase لجميع الزوار
if (window.db) {
  window.db.collection("site").doc("primeRPData").onSnapshot((doc) => {
    if (doc.exists && doc.data()) {
      data = doc.data();
      render();
    }
  });
}
})();
